name: docker

on:
  release:
    types: [published]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: base
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: timche/csgo
          tags: latest,${{ github.event.release.tag_name }}
          path: ./base
      - name: sourcemod
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: timche/csgo
          tags: sourcemod,sourcemod-${{ github.event.release.tag_name }}
          path: ./sourcemod
      - name: pug-practice
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: timche/csgo
          tags: pug-practice,pug-practice-${{ github.event.release.tag_name }}
          path: ./pug-practice
